[package]
name = "iridium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.11"
env_logger = "0.10.0"
log = "0.4.19"
nom = "7.1.3"
nom-supreme = "0.8.0"
thiserror = "1.0.43"
